#define AMBITION_INTENSITY_STEALTH 2
#define AMBITION_INTENSITY_MILD 3
#define AMBITION_INTENSITY_MEDIUM 5
#define AMBITION_INTENSITY_SEVERE 12
#define AMBITION_INTENSITY_EXTREME 20

#define MAX_AMBITION_FLAVOR_LEN 4000
