#define JUKEBOX_MAX_RANGE 22
#define JUKEBOX_FALLOFF_DISTANCE 6
#define JUKEBOX_FALLOFF_EXPONENT 0.5

#define JUKEBOX_VIEW_RANGE 7
#define JUKEBOX_ECHO_RANGE 10

#define JUKEBOX_ECHO_VOLUME_MODIFIER 0.85

#define JUKEBOX_NO_POSITIONAL_RANGE 3

#define JUKEBOX_MULTI_Z_DISTANCE_MULTIPLICATOR 9

#define MINIMUM_JUKEBOX_PRESSURE_FACTOR 0.2
