#define MOLD_CORE_DEATH_DO_NOTHING 1
#define MOLD_CORE_DEATH_SLOW_DECAY 2
#define MOLD_CORE_DEATH_DELETE_ALL 3

#define FACTION_MOLD "mold"

#define FIRE_MOLD_COLOR "#C50"
#define EMP_MOLD_COLOR "#0B9"
#define FUNGUS_MOLD_COLOR "#A85"
#define TOXIC_MOLD_COLOR "#480"
